basicsalary=50000
print("basic salary is=", basicsalary)
DA=0.15*basicsalary
print("salary of da is=", DA)
HRA=0.2*basicsalary
print("salary of HRA is=", HRA)
PF=1000
print("salary of PF=", PF)
MA=0.05*basicsalary
print("salary of MA=", MA)
final=DA+HRA+MA-PF
print("final salary is=", final)